/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedAdminImportQueueRouteImport } from './routes/_authenticated/admin-import-queue'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicRatesRouteImport } from './routes/api/public/rates'
import { Route as ApiPublicHooksProcessImportQueueRouteImport } from './routes/api/public/hooks/process-import-queue'
import { Route as ApiPublicHooksDigisellerSyncRouteImport } from './routes/api/public/hooks/digiseller-sync'
import { Route as ApiPublicHooksDigisellerImportRouteImport } from './routes/api/public/hooks/digiseller-import'
import { Route as ApiPublicHooksDigisellerAvailabilityRouteImport } from './routes/api/public/hooks/digiseller-availability'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminImportQueueRoute =
  AuthenticatedAdminImportQueueRouteImport.update({
    id: '/admin-import-queue',
    path: '/admin-import-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRatesRoute = ApiPublicRatesRouteImport.update({
  id: '/api/public/rates',
  path: '/api/public/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessImportQueueRoute =
  ApiPublicHooksProcessImportQueueRouteImport.update({
    id: '/api/public/hooks/process-import-queue',
    path: '/api/public/hooks/process-import-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDigisellerSyncRoute =
  ApiPublicHooksDigisellerSyncRouteImport.update({
    id: '/api/public/hooks/digiseller-sync',
    path: '/api/public/hooks/digiseller-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDigisellerImportRoute =
  ApiPublicHooksDigisellerImportRouteImport.update({
    id: '/api/public/hooks/digiseller-import',
    path: '/api/public/hooks/digiseller-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDigisellerAvailabilityRoute =
  ApiPublicHooksDigisellerAvailabilityRouteImport.update({
    id: '/api/public/hooks/digiseller-availability',
    path: '/api/public/hooks/digiseller-availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-import-queue': typeof AuthenticatedAdminImportQueueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/hooks/digiseller-availability': typeof ApiPublicHooksDigisellerAvailabilityRoute
  '/api/public/hooks/digiseller-import': typeof ApiPublicHooksDigisellerImportRoute
  '/api/public/hooks/digiseller-sync': typeof ApiPublicHooksDigisellerSyncRoute
  '/api/public/hooks/process-import-queue': typeof ApiPublicHooksProcessImportQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-import-queue': typeof AuthenticatedAdminImportQueueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/hooks/digiseller-availability': typeof ApiPublicHooksDigisellerAvailabilityRoute
  '/api/public/hooks/digiseller-import': typeof ApiPublicHooksDigisellerImportRoute
  '/api/public/hooks/digiseller-sync': typeof ApiPublicHooksDigisellerSyncRoute
  '/api/public/hooks/process-import-queue': typeof ApiPublicHooksProcessImportQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-import-queue': typeof AuthenticatedAdminImportQueueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/hooks/digiseller-availability': typeof ApiPublicHooksDigisellerAvailabilityRoute
  '/api/public/hooks/digiseller-import': typeof ApiPublicHooksDigisellerImportRoute
  '/api/public/hooks/digiseller-sync': typeof ApiPublicHooksDigisellerSyncRoute
  '/api/public/hooks/process-import-queue': typeof ApiPublicHooksProcessImportQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/reviews'
    | '/admin'
    | '/admin-import-queue'
    | '/product/$slug'
    | '/api/public/rates'
    | '/api/public/hooks/digiseller-availability'
    | '/api/public/hooks/digiseller-import'
    | '/api/public/hooks/digiseller-sync'
    | '/api/public/hooks/process-import-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/reviews'
    | '/admin'
    | '/admin-import-queue'
    | '/product/$slug'
    | '/api/public/rates'
    | '/api/public/hooks/digiseller-availability'
    | '/api/public/hooks/digiseller-import'
    | '/api/public/hooks/digiseller-sync'
    | '/api/public/hooks/process-import-queue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/reviews'
    | '/_authenticated/admin'
    | '/_authenticated/admin-import-queue'
    | '/product/$slug'
    | '/api/public/rates'
    | '/api/public/hooks/digiseller-availability'
    | '/api/public/hooks/digiseller-import'
    | '/api/public/hooks/digiseller-sync'
    | '/api/public/hooks/process-import-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  FaqRoute: typeof FaqRoute
  ReviewsRoute: typeof ReviewsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicRatesRoute: typeof ApiPublicRatesRoute
  ApiPublicHooksDigisellerAvailabilityRoute: typeof ApiPublicHooksDigisellerAvailabilityRoute
  ApiPublicHooksDigisellerImportRoute: typeof ApiPublicHooksDigisellerImportRoute
  ApiPublicHooksDigisellerSyncRoute: typeof ApiPublicHooksDigisellerSyncRoute
  ApiPublicHooksProcessImportQueueRoute: typeof ApiPublicHooksProcessImportQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-import-queue': {
      id: '/_authenticated/admin-import-queue'
      path: '/admin-import-queue'
      fullPath: '/admin-import-queue'
      preLoaderRoute: typeof AuthenticatedAdminImportQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/rates': {
      id: '/api/public/rates'
      path: '/api/public/rates'
      fullPath: '/api/public/rates'
      preLoaderRoute: typeof ApiPublicRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-import-queue': {
      id: '/api/public/hooks/process-import-queue'
      path: '/api/public/hooks/process-import-queue'
      fullPath: '/api/public/hooks/process-import-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessImportQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/digiseller-sync': {
      id: '/api/public/hooks/digiseller-sync'
      path: '/api/public/hooks/digiseller-sync'
      fullPath: '/api/public/hooks/digiseller-sync'
      preLoaderRoute: typeof ApiPublicHooksDigisellerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/digiseller-import': {
      id: '/api/public/hooks/digiseller-import'
      path: '/api/public/hooks/digiseller-import'
      fullPath: '/api/public/hooks/digiseller-import'
      preLoaderRoute: typeof ApiPublicHooksDigisellerImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/digiseller-availability': {
      id: '/api/public/hooks/digiseller-availability'
      path: '/api/public/hooks/digiseller-availability'
      fullPath: '/api/public/hooks/digiseller-availability'
      preLoaderRoute: typeof ApiPublicHooksDigisellerAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminImportQueueRoute: typeof AuthenticatedAdminImportQueueRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminImportQueueRoute: AuthenticatedAdminImportQueueRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  FaqRoute: FaqRoute,
  ReviewsRoute: ReviewsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicRatesRoute: ApiPublicRatesRoute,
  ApiPublicHooksDigisellerAvailabilityRoute:
    ApiPublicHooksDigisellerAvailabilityRoute,
  ApiPublicHooksDigisellerImportRoute: ApiPublicHooksDigisellerImportRoute,
  ApiPublicHooksDigisellerSyncRoute: ApiPublicHooksDigisellerSyncRoute,
  ApiPublicHooksProcessImportQueueRoute: ApiPublicHooksProcessImportQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
